"""
Interactive CLI for generating Spotify playlists via the backend API.

It prompts you for a vibe description, calls the backend `/vibe/generate_llm`
endpoint to get tracks for that vibe, creates a playlist via
`/playlist/create_from_tracks`, and prints the resulting Spotify link.
Press Ctrl+C to exit the loop.

By default the Spotify user ID (UID) is hard‑coded below.  You can override it
at runtime by setting the environment variable SPOTIFY_UID before running the script,
or by importing this module and setting `playlist_chat.UID` from another file.
"""

import os
import httpx
import time
from typing import List, Dict, Any

# Base URL of your FastAPI backend
BASE_URL = "http://127.0.0.1:3001"

# Default Spotify user ID; can be overridden via SPOTIFY_UID env var or by monkey‑patching
UID = os.environ.get("SPOTIFY_UID", "21e67joy67geof4pyptwrxtmy")


def generate_tracks_from_vibe(vibe_text: str, count: int = 20) -> List[Dict[str, Any]]:
    """
    Call the /vibe/generate_llm endpoint to get a list of track dicts for the given vibe.
    Each dict has keys: id, uri, name, artist, image, etc.
    """
    payload = {"user": UID, "vibeText": vibe_text, "count": count}
    response = httpx.post(f"{BASE_URL}/vibe/generate_llm", json=payload, timeout=30)
    response.raise_for_status()
    data = response.json()
    return data.get("tracks", [])


def create_playlist_for_tracks(tracks: List[Dict[str, Any]], vibe_text: str) -> str:
    """
    Create a new playlist for the given list of track dicts.
    Returns the Spotify playlist URL.
    """
    uris = [t["uri"] for t in tracks if "uri" in t]
    if not uris:
        raise RuntimeError("No valid track URIs to add to a playlist.")
    playlist_name = f"{vibe_text} – {time.strftime('%Y-%m-%d %H:%M')}"
    payload = {
        "user": UID,
        "name": playlist_name,
        "description": f"Generated by our hackathon app for vibe: {vibe_text}",
        "public": True,
        "trackUris": uris,
    }
    response = httpx.post(f"{BASE_URL}/playlist/create_from_tracks", json=payload, timeout=30)
    response.raise_for_status()
    data = response.json()
    return data.get("url", "")


def interactive_session() -> None:
    """
    Run an interactive loop: ask the user for a vibe description, generate tracks,
    create a playlist, and print the URL. Press Ctrl+C to exit.
    """
    print("🎶 Playlist Chat CLI")
    print(f"Using Spotify user ID: {UID}")
    print("Enter a vibe description (e.g. 'night drive back home') and press Enter.")
    try:
        while True:
            prompt = input("\nYour vibe: ").strip()
            if not prompt:
                print("Please type something or press Ctrl+C to exit.")
                continue
            print("Generating tracks…")
            tracks = generate_tracks_from_vibe(prompt, count=20)
            print(f"Got {len(tracks)} tracks; creating playlist…")
            url = create_playlist_for_tracks(tracks, prompt)
            print(f"✅ Playlist created: {url}")
    except KeyboardInterrupt:
        print("\nExiting. Goodbye!")
    except httpx.HTTPError as e:
        print(f"HTTP error: {e}")
    except Exception as e:
        print(f"Error: {e}")
