import os
import httpx
import time
from typing import List, Dict, Any
# testing in a vaccum plz ignore

BASE_URL = "http://127.0.0.1:3001"

UID = os.environ.get("SPOTIFY_UID", "21e67joy67geof4pyptwrxtmy")


def generate_tracks_from_vibe(vibe_text: str, count: int = 20) -> List[Dict[str, Any]]:
    payload = {"user": UID, "vibeText": vibe_text, "count": count}
    response = httpx.post(f"{BASE_URL}/vibe/generate_llm", json=payload, timeout=30)
    response.raise_for_status()
    data = response.json()
    return data.get("tracks", [])


def create_playlist_for_tracks(tracks: List[Dict[str, Any]], vibe_text: str) -> str:
    uris = [t["uri"] for t in tracks if "uri" in t]
    if not uris:
        raise RuntimeError("No valid track URIs to add to a playlist.")
    playlist_name = f"{vibe_text} – {time.strftime('%Y-%m-%d %H:%M')}"
    payload = {
        "user": UID,
        "name": playlist_name,
        "description": f"Generated by our hackathon app for vibe: {vibe_text}",
        "public": True,
        "trackUris": uris,
    }
    response = httpx.post(f"{BASE_URL}/playlist/create_from_tracks", json=payload, timeout=30)
    response.raise_for_status()
    data = response.json()
    return data.get("url", "")


def interactive_session() -> None:
    print("🎶 Playlist Chat CLI")
    print(f"Using Spotify user ID: {UID}")
    print("Enter a vibe description and press Enter.")
    try:
        while True:
            prompt = input("\nYour vibe: ").strip()
            if not prompt:
                print("Please type something or press Ctrl+C to exit.")
                continue
            print("Generating tracks…")
            tracks = generate_tracks_from_vibe(prompt, count=20)
            print(f"Got {len(tracks)} tracks; creating playlist…")
            url = create_playlist_for_tracks(tracks, prompt)
            print(f"Playlist created: {url}")
    except KeyboardInterrupt:
        print("\nGoodbye!")
    except httpx.HTTPError as e:
        print(f"HTTP error: {e}")
    except Exception as e:
        print(f"Error: {e}")
